Test search page, creating tests
PerfCake/PerfRepo pull request #66
Opened 2017-01-05 00:04 UTC by grunwjir

Test search page was improved, it supports list and card view. UI changes. 

The page for test detail was created, it is possible to add/edit/remove metrics and alerts. Subscribing to test alerts is working. UI of this page is temporary, will be changed.

Form validation for tests, metrics and alerts was implemented.

2017-01-05 00:07 UTC, grunwjir commented on model/src/main/java/org/perfrepo/model/to/OrderBy.java
Can I rename this?

2017-01-05 07:16 UTC, Holmistr commented on model/src/main/java/org/perfrepo/model/to/OrderBy.java
It's actually better if you rename this :)

2017-01-11 11:40 UTC, Holmistr requested changes

2017-01-11 11:40 UTC, Holmistr commented on model/src/main/java/org/perfrepo/dto/test_execution/TestExecutionGroupValueDto.java
> +public class TestExecutionGroupValueDto {
Could you please explain purpose of this class? I would also rename it to ValueGroupDto, you don't have to put "TestExecution" everywhere

2017-01-11 11:40 UTC, Holmistr commented on model/src/main/java/org/perfrepo/dto/test_execution/TestExecutionSearchParams.java
>  public class TestExecutionSearchParams {
I think TestExecutionSearchCriteria is more descriptible, but that's a minor comment.

2017-01-11 11:40 UTC, Holmistr commented on model/src/main/java/org/perfrepo/dto/test_execution/TestExecutionValueDto.java
> +public class TestExecutionValueDto {
Rename to ValueDto. Values are present only for test execution, it's obvious.

2017-01-11 11:40 UTC, Holmistr commented on web/pom.xml
> +            <artifactId>frontend-maven-plugin</artifactId>
Could you please very shortly explain, what the plugin basically does? It's just I have never used it before, nothing wrong with the usage at all :)

2017-01-11 11:40 UTC, Holmistr commented on web/src/main/java/org/perfrepo/web/adapter/dummy_impl/builders/TestExecutionValueDtoBuilder.java
> +public class TestExecutionValueDtoBuilder {
Rename, see previous comments.

2017-01-11 11:40 UTC, Holmistr commented on web/src/main/java/org/perfrepo/web/rest/endpoints/TestExecutionRestApi.java
> +
Extra empty line

2017-01-11 12:38 UTC, Holmistr commented
I've placed some minor comments, but let me add some more high-level regarding tests pages:
* the listing is not expanding to full width on my monitor, looks like the width is fixed somehow and it looks IMHO weird (see attached screenshot)
* add headings to the columns of the table (like test name, test UID)
* the test name should be clickable on its own redirecting to the test detail
* There is button "Test detail". First - it can be just "Detail" with maybe different icon, but I would also create buttons "Edit" and "Delete" (also remove "test", it's obvious) and now hide them into dropdown menu. However, I really like the dropdown menu and the "Create test execution" and "Show test executions" should remain there, that's absolutely brilliant :)
* there is a small arrow on each row showing more information. To me it doesn't make sense to duplicate the information about the test there. However, I really like the idea of this dropdown and I think we can use it much better. It could show last x (let's say 3) test executions that were run for this test. Just a mini-table with 3 rows saying something like "Last 3 test executions" and listing - execution name, execution date and tags. That would be truly awesome, hopefully it's not too much work. And it's important that this information would be lazily-loaded, not preloaded for every test in advance. 
* Also the arrow is not vertically centered with the test name, so it looks a bit weird.
* regarding the card view - I cannot imagine a usecase how it could be useful in this situation, hence I would remove it

Moving on to test detail page:
* the right align of "Uid", "Group" etc. is done on purpose? Looks non-traditional to me :-D I would prefer left align. Also please use UID everywhere :)
* listings of metric should contain also the description of the metric, it's actually quite common that you look at that to find out, what it actually means.
* listings of alerts - basically the same as above, I would show name of the alert and description, everything else can be hidden until "Edit" is clicked.
* even here (test detail) the page is narrower on my screen, perhaps something more general is not set up correctly (see attached screenshot)

That's all I've got. I know that some of the comments are really minor, please don't take it bad, I think it's an awesome work, just want to have it perfect :)

![snimek z 2017-01-11 13-35-29](https://cloud.githubusercontent.com/assets/4253850/21848806/0921ee8c-d803-11e6-9a43-f0112b164f6e.png)
![snimek z 2017-01-11 13-35-33](https://cloud.githubusercontent.com/assets/4253850/21848809/0bcb7e64-d803-11e6-9af1-16da4594f4db.png)

2017-01-15 20:11 UTC, grunwjir commented on model/src/main/java/org/perfrepo/dto/test_execution/TestExecutionGroupValueDto.java
> +public class TestExecutionGroupValueDto {
It represents a group of test execution values. This group is for each test metric, therefore the values are grouped by a metric.

2017-01-15 20:12 UTC, grunwjir commented on model/src/main/java/org/perfrepo/dto/test_execution/TestExecutionValueDto.java
> +public class TestExecutionValueDto {
Ok, renamed.

2017-01-15 20:19 UTC, grunwjir commented on web/pom.xml
> +            <artifactId>frontend-maven-plugin</artifactId>
It downloads and installs Node, NPM locally for this project. It runs Bower and executes Gulp build task.

2017-01-15 20:19 UTC, grunwjir commented on web/src/main/java/org/perfrepo/web/adapter/dummy_impl/builders/TestExecutionValueDtoBuilder.java
> +public class TestExecutionValueDtoBuilder {
Renamed.

2017-01-15 20:48 UTC, grunwjir commented
Answers to your comments:
> - the listing is not expanding to full width on my monitor, looks like the width is fixed somehow and 
it looks IMHO weird (see attached screenshot)

Repaired to full width of a screen. It was set to maximum width 1140px, but it was bad idea. 

> - add headings to the columns of the table (like test name, test UID)

It is [list view component](https://www.patternfly.org/pattern-library/content-views/list-view/#/_design) and it does not support headings. I know that my solution is not ideal, will be improved.

> - the test name should be clickable on its own redirecting to the test detail
> - There is button "Test detail". First - it can be just "Detail" with maybe different icon, but I would also create buttons "Edit" and "Delete" (also remove "test", it's obvious) and now hide them into dropdown menu. However, I really like the dropdown menu and the "Create test execution" and "Show test executions" should remain there, that's absolutely brilliant :)

Ok, resolved.

> - there is a small arrow on each row showing more information. To me it doesn't make sense to duplicate the information about the test there. However, I really like the idea of this dropdown and I think we can use it much better. It could show last x (let's say 3) test executions that were run for this test. Just a mini-table with 3 rows saying something like "Last 3 test executions" and listing - execution name, execution date and tags. That would be truly awesome, hopefully it's not too much work. And it's important that this information would be lazily-loaded, not preloaded for every test in advance.
>  - Also the arrow is not vertically centered with the test name, so it looks a bit weird.

I agree and show last x test executions is great idea, I will add it (next PR).

> - regarding the card view - I cannot imagine a usecase how it could be useful in this situation, hence I would remove it

The card view was removed.

> Moving on to test detail page:
...

Test detail page will be completely redesigned, next PR.

Thank you very much for your revision :)

2017-01-15 21:48 UTC, grunwjir commented on model/src/main/java/org/perfrepo/dto/test_execution/TestExecutionSearchParams.java
>  public class TestExecutionSearchParams {
Renamed

2017-01-19 08:11 UTC, Holmistr commented
Changes looks good to me, I have noticed two more things:
* I would also want to see to which group the tests is assigned in the listings, hence add another column like "Group".
* I noticed that when I deploy the application to the server and access the "base" URL, the dashboard can be seen without login. However when I want to access anything else, login is finally required. This is something that we must not forget to fix :)

Please add at least the group column, note somewhere the login thing and we're good to integrate this PR.

2017-01-24 13:05 UTC, merged